controller_list:
  - name: fake_didik_scara_controller
    type: $(arg execution_type)
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
initial:  # Define initial robot poses.
  - group: didik_scara
    pose: rest